# Generated by Django 5.1.5 on 2025-01-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('table_data', models.TextField()),
                ('graph', models.ImageField(blank=True, null=True, upload_to='graphs/')),
            ],
        ),
    ]
