# Generated by Django 5.1.5 on 2025-01-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('table_data', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='CountByCity',
        ),
        migrations.DeleteModel(
            name='CountByCityProf',
        ),
        migrations.DeleteModel(
            name='CountByYear',
        ),
        migrations.DeleteModel(
            name='CountByYearProf',
        ),
        migrations.DeleteModel(
            name='Graph',
        ),
        migrations.DeleteModel(
            name='SalaryByCity',
        ),
        migrations.DeleteModel(
            name='SalaryByCityProf',
        ),
        migrations.DeleteModel(
            name='SalaryByYear',
        ),
        migrations.DeleteModel(
            name='SalaryByYearProf',
        ),
        migrations.DeleteModel(
            name='TopSkills',
        ),
    ]
