# Generated by Django 5.1.5 on 2025-01-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_statistics_delete_countbycity_delete_countbycityprof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='graph',
            field=models.ImageField(blank=True, null=True, upload_to='graphs/'),
        ),
    ]
